# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.IntegerField()),
                ('meeting_name', models.CharField(max_length=256)),
                ('meeting_sub', models.CharField(max_length=256)),
                ('meeting_text', models.TextField(max_length=1024)),
            ],
        ),
    ]
