# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0003_auto_20190711_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_meeting',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='create_meeting',
            name='meeting_name',
            field=models.CharField(choices=[('planning meeting', 'Planning Meeting'), ('exam committee meeting', 'Exam Committee Meeting'), ('Event Meeting', 'Other'), ('ac meeting', 'AC Meeting'), ('general meeting', 'General Meeting')], default='General Meeting', max_length=256),
        ),
        migrations.AlterField(
            model_name='create_meeting',
            name='meeting_text',
            field=models.TextField(max_length=500),
        ),
    ]
