# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_auto_20190711_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='create_meeting',
            name='meeting_name',
            field=models.CharField(choices=[('Planning Meeting', 'Planning Meeting'), ('Exam Committee Meeting', 'Exam Committee Meeting'), ('Event Meeting', 'Event Meeting'), ('AC Meeting', 'AC Meeting'), ('General Meeting', 'General Meeting'), ('Other', 'Other')], default='General Meeting', max_length=256),
        ),
        migrations.AddField(
            model_name='committee_member',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='meeting_app.Create_Meeting'),
        ),
    ]
