# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0005_auto_20190712_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda1', models.TextField(max_length=200)),
                ('decision1', models.TextField(max_length=200)),
                ('agenda2', models.TextField(max_length=200)),
                ('decision2', models.TextField(max_length=200)),
                ('agenda3', models.TextField(max_length=200)),
                ('decision3', models.TextField(max_length=200)),
                ('agenda4', models.TextField(max_length=200)),
                ('decision4', models.TextField(max_length=200)),
                ('agenda5', models.TextField(max_length=200)),
                ('decision5', models.TextField(max_length=200)),
                ('resulaton_sub', models.ForeignKey(default='meeting_sub', on_delete=django.db.models.deletion.CASCADE, related_name='resulations', to='meeting_app.Create_Meeting')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
